# Generated by Django 5.2.8 on 2025-12-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(default='', max_length=100)),
                ('artist_name', models.CharField(default='', max_length=255)),
                ('track_name', models.CharField(default='', max_length=255)),
                ('track_id', models.CharField(max_length=64)),
                ('popularity', models.PositiveSmallIntegerField(default=0, help_text='0-100')),
                ('acousticness', models.FloatField(default=0.0)),
                ('danceability', models.FloatField(default=0.0)),
                ('duration_ms', models.PositiveIntegerField(default=0, help_text='Duration in milliseconds')),
                ('energy', models.FloatField(default=0.0)),
                ('instrumentalness', models.FloatField(default=0.0)),
            ],
        ),
    ]
